[package]
name = "elcc"
version = "0.1.0"
edition = "2024"
authors = ["Yusuke Matsushita <ysk.m24t@gmail.com>"]
description = "Elc compiler based on rustc."

[dependencies]
color-print = "0.3.7"
clap = { version = "4.5.47", features = ["derive"] }
clap_complete = "4.5.57"
regex = "1.11.2"

[package.metadata.rust-analyzer]
rustc_private = true
