[package]
name = "elcc"
version = "0.1.0"
edition = "2024"
authors = ["Yusuke Matsushita <ysk.m24t@gmail.com>"]
description = "Elc compiler based on rustc."

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
clap_complete = "4.5.57"
regex = "1.11.2"
lazy_static = "1.5.0"
yansi = "1.0.1"

[package.metadata.rust-analyzer]
rustc_private = true
