[package]
name = "elc-examples"
version = "0.1.0"
edition = "2024"
authors = ["Yusuke Matsushita <ysk.m24t@gmail.com>"]
description = "Examples for Elc"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
